# Generated by Django 2.2.5 on 2021-07-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuname',
            options={'verbose_name_plural': 'menu'},
        ),
    ]
