# Generated by Django 2.2.5 on 2021-07-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0002_auto_20210713_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandname',
            options={'verbose_name_plural': 'Brand_ Name'},
        ),
    ]
